/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ziezix360.hm.patient;

import com.ziezix360.hm.patient.dao.intf.PatientDao;
import com.ziezix360.hm.patient.dao.model.Patient;
import org.junit.BeforeClass;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class PatientAppTest {
    @BeforeClass
    public static void runApp() {
        PatientApp.main(new String[]{""});
    }

    @Test public void testHasUserPaulExist() {

        PatientDao patientDao = PatientApp.context.getBean(PatientDao.class);
        Patient patient = new Patient();
        patient.setId(1);
        patient = patientDao.read(patient);

        assertNotEquals(null, patient);
        assertEquals("PAUL", patient.getName().trim());

    }

    @Test public void testHasTwoUsers() {

        PatientDao patientDao = PatientApp.context.getBean(PatientDao.class);
        List<Patient> userList = patientDao.list();

        assertNotEquals(null, userList);
        assertTrue(userList.size() >= 2);

    }}
