/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ziezix360.hm.user;

import com.ziezix360.hm.user.dao.intf.UserDao;
import com.ziezix360.hm.user.dao.model.User;
import org.junit.BeforeClass;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class UserAppTest {


    @BeforeClass public static void runApp() {
        UserApp.main(new String[]{""});
    }

    @Test public void testHasUserPaulExist() {

        UserDao userDao = UserApp.context.getBean(UserDao.class);
        User user = new User();
        user.setId(1);
        user = userDao.read(user);

        assertNotEquals(null, user);
        assertEquals("PAUL", user.getName().trim());

    }

    @Test public void testHasTwoUsers() {

        UserDao userDao = UserApp.context.getBean(UserDao.class);
        List<User> userList = userDao.list();

        assertNotEquals(null, userList);
        assertTrue(2 <= userList.size());

    }
}
